In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_modified/iot.csv')
df.shape

(53759, 27)

In [3]:
df

,unit_ID,cycles,time_to_deterioration,setting_1,setting_2,setting_3,T2,T24,T30,T50,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfR_dmd,W31,W32
0,1,1,148,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,147,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,146,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,145,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,144,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,4,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,...,314.05,2389.02,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189
53755,260,313,3,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,...,371.22,2388.42,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454
53756,260,314,2,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,...,163.74,2030.33,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503
53757,260,315,1,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,...,164.37,2030.35,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729
53758,260,316,0,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,...,183.09,2390.38,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446

In [5]:
df[df['unit_ID']==1]

,unit_ID,cycles,time_to_deterioration,setting_1,setting_2,setting_3,T2,T24,T30,T50,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfR_dmd,W31,W32
0,1,1,148,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,147,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,146,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,145,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,144,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,1,145,4,35.0007,0.8402,100.0,449.44,556.59,1376.19,1152.04,...,182.61,2387.77,8050.29,9.4189,0.02,338,2223,100.00,14.72,8.8240
145,1,146,3,10.0006,0.2516,100.0,489.05,605.94,1511.92,1326.50,...,370.52,2388.43,8113.02,8.7345,0.03,372,2319,100.00,28.16,16.9984
146,1,147,2,25.0005,0.6200,60.0,462.54,537.50,1268.62,1057.88,...,164.56,2027.97,7866.66,10.9764,0.02,310,1915,84.93,14.34,8.4476
147,1,148,1,0.0024,0.0013,100.0,518.67,643.73,1605.33,1425.76,...,519.76,2388.31,8115.88,8.5240,0.03,397,2388,100.00,38.55,23.0079
148,1,149,0,42.0017,0.8414,100.0,445.00,550.49,1366.01,1149.81,...,129.55,2387.40,8066.19,9.4765,0.02,332,2212,100.00,10.45,6.2285

In [7]:
df[['unit_ID','cycles']].describe()

            unit_ID        cycles
count  53759.000000  53759.000000
mean     131.082981    109.154746
std       74.463862     69.180569
min        1.000000      1.000000
25%       68.000000     52.000000
50%      131.000000    104.000000
75%      195.000000    157.000000
max      260.000000    378.000000

In [2]:
df_mod = pd.read_csv('data_modified/modeling_engine_partial.csv')
df_mod.shape

(2216, 51)

In [3]:
df_mod

,unit_ID,cycles,time_to_deterioration,setting_1-mean,setting_2-mean,setting_3-mean,T2-mean,T24-mean,T30-mean,T50-mean,...,phi-sd,NRf-sd,NRc-sd,BPR-sd,farB-sd,htBleed-sd,Nf_dmd-sd,PCNfR_dmd-sd,W31-sd,W32-sd
0,1,120,29,25.883372,0.628304,95.2,470.9576,578.3988,1418.8880,1202.9252,...,138.767936,119.374676,73.805650,0.683085,0.004899,27.405900,137.158874,4.998154,9.900593,5.943908
1,1,124,25,23.723044,0.599132,95.2,474.5672,582.9664,1430.5744,1216.2684,...,135.328416,119.396075,74.369270,0.694186,0.005066,27.372310,139.045856,4.998154,9.662809,5.776876
2,1,125,24,25.003032,0.622780,95.2,472.8052,580.7724,1424.8056,1209.4468,...,136.629380,119.386880,73.064325,0.680040,0.005000,27.381563,138.240648,4.998154,9.763562,5.845288
3,2,153,116,28.482604,0.707784,95.2,467.1748,573.5012,1403.4784,1177.5300,...,113.389744,119.327653,70.937353,0.605923,0.002769,23.734785,130.876316,4.998154,8.172547,4.884392
4,2,173,96,24.882896,0.615056,92.0,472.4908,577.3712,1409.7260,1193.0236,...,130.746788,146.879170,91.624069,0.792373,0.004359,28.238685,162.331995,6.152302,9.339384,5.622226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,260,130,186,23.242544,0.537328,92.0,473.4632,578.0828,1411.8896,1196.9112,...,139.838800,146.897945,95.690991,0.849630,0.004899,28.817703,163.335207,6.152302,10.077390,6.040323
2212,260,156,160,28.923252,0.657436,92.0,462.9084,565.0076,1376.7656,1157.8228,...,110.566501,146.876920,91.778338,0.773675,0.004082,24.031785,148.374279,6.152302,8.032487,4.822330
2213,260,169,147,21.882824,0.498996,95.2,474.9688,583.0120,1428.7052,1218.3416,...,152.139911,119.310863,80.812091,0.758114,0.005066,29.611541,140.898048,4.998154,10.872344,6.556184
2214,260,172,144,22.882808,0.531812,93.6,473.9940,580.4292,1418.0300,1205.7976,...,151.877535,134.599987,88.278170,0.815417,0.004899,30.419950,154.523763,5.638678,10.829984,6.520069
2215,260,186,130,21.043268,0.518572,90.4,476.0600,580.2484,1414.9804,1201.4368,...,139.090953,156.813966,102.638904,0.916410,0.004899,31.272299,176.476656,6.568861,9.847304,5.927130

In [4]:
df = pd.read_csv('data_modified/iot.csv')
print(df.shape)
df.head()

(53759, 27)

,unit_ID,cycles,time_to_deterioration,setting_1,setting_2,setting_3,T2,T24,T30,T50,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfR_dmd,W31,W32
0,1,1,148,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,147,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,146,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,145,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,144,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286

In [8]:
df1 = df[df["unit_ID"]==1]
df1

,unit_ID,cycles,time_to_deterioration,setting_1,setting_2,setting_3,T2,T24,T30,T50,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfR_dmd,W31,W32
0,1,1,148,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,147,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,146,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,145,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,144,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,1,145,4,35.0007,0.8402,100.0,449.44,556.59,1376.19,1152.04,...,182.61,2387.77,8050.29,9.4189,0.02,338,2223,100.00,14.72,8.8240
145,1,146,3,10.0006,0.2516,100.0,489.05,605.94,1511.92,1326.50,...,370.52,2388.43,8113.02,8.7345,0.03,372,2319,100.00,28.16,16.9984
146,1,147,2,25.0005,0.6200,60.0,462.54,537.50,1268.62,1057.88,...,164.56,2027.97,7866.66,10.9764,0.02,310,1915,84.93,14.34,8.4476
147,1,148,1,0.0024,0.0013,100.0,518.67,643.73,1605.33,1425.76,...,519.76,2388.31,8115.88,8.5240,0.03,397,2388,100.00,38.55,23.0079
148,1,149,0,42.0017,0.8414,100.0,445.00,550.49,1366.01,1149.81,...,129.55,2387.40,8066.19,9.4765,0.02,332,2212,100.00,10.45,6.2285

In [15]:
df1 = df1[(df1['cycles']>=95) & (df1['cycles']<=120)]
df1

,unit_ID,cycles,time_to_deterioration,setting_1,setting_2,setting_3,T2,T24,T30,T50,...,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNfR_dmd,W31,W32
94,1,95,54,35.0058,0.8403,100.0,449.44,555.64,1369.57,1136.49,...,182.37,2387.76,8058.75,9.3649,0.02,335,2223,100.00,14.80,8.8716
95,1,96,53,42.0062,0.8402,100.0,445.00,549.65,1358.37,1125.38,...,130.49,2387.55,8067.54,9.3981,0.02,330,2212,100.00,10.49,6.3469
96,1,97,52,42.0015,0.8413,100.0,445.00,549.43,1354.86,1127.44,...,130.44,2387.63,8071.46,9.3681,0.02,329,2212,100.00,10.75,6.3409
97,1,98,51,0.0025,0.0015,100.0,518.67,643.26,1593.43,1409.77,...,521.22,2388.17,8124.58,8.4587,0.03,395,2388,100.00,38.62,23.3025
98,1,99,50,10.0051,0.2502,100.0,489.05,604.97,1501.19,1309.55,...,371.05,2388.25,8119.05,8.6636,0.03,369,2319,100.00,28.53,17.1145
99,1,100,49,20.0027,0.7000,100.0,491.19,607.60,1488.43,1259.11,...,314.17,2388.06,8048.36,9.2490,0.03,367,2324,100.00,24.51,14.6742
100,1,101,48,42.0021,0.8400,100.0,445.00,549.99,1349.48,1135.38,...,130.44,2387.62,8066.89,9.3842,0.02,330,2212,100.00,10.50,6.4038
101,1,102,47,35.0063,0.8400,100.0,449.44,555.90,1376.66,1139.31,...,182.22,2387.77,8059.02,9.3595,0.02,334,2223,100.00,14.86,8.8523
102,1,103,46,20.0057,0.7010,100.0,491.19,607.32,1495.89,1258.36,...,314.23,2388.13,8045.91,9.2488,0.03,366,2324,100.00,24.22,14.7405
103,1,104,45,35.0078,0.8400,100.0,449.44,556.29,1362.75,1129.45,...,182.92,2387.77,8056.86,9.3655,0.02,335,2223,100.00,14.81,8.9265
104,1,105,44,20.0052,0.7000,100.0,491.19,607.04,1487.94,1261.08,...,314.16,2388.10,8045.38,9.2580,0.03,364,2324,100.00,24.37,14.5177
105,1,106,43,0.0008,0.0019,100.0,518.67,643.12,1590.38,1414.45,...,520.52,2388.12,8122.68,8.4556,0.03,394,2388,100.00,38.68,23.2542
106,1,107,42,35.0037,0.8411,100.0,449.44,555.85,1365.70,1139.21,...,183.02,2387.80,8064.94,9.3838,0.02,337,2223,100.00,14.85,8.9967
107,1,108,41,41.9998,0.8414,100.0,445.00,550.09,1362.34,1133.92,...,130.73,2387.70,8066.37,9.3829,0.02,331,2212,100.00,10.42,6.3999
108,1,109,40,41.9991,0.8419,100.0,445.00,549.88,1360.26,1137.95,...,130.97,2387.66,8063.48,9.3712,0.02,332,2212,100.00,10.47,6.3742
109,1,110,39,20.0074,0.7019,100.0,491.19,607.79,1489.60,1267.13,...,314.53,2388.03,8049.06,9.2481,0.03,368,2324,100.00,24.30,14.6406
110,1,111,38,0.0027,0.0017,100.0,518.67,643.25,1595.96,1419.21,...,520.65,2388.18,8117.58,8.4483,0.03,393,2388,100.00,38.47,23.1974
111,1,112,37,42.0049,0.8400,100.0,445.00,549.91,1360.02,1137.89,...,130.77,2387.58,8069.51,9.4154,0.02,331,2212,100.00,10.64,6.4053
112,1,113,36,0.0013,0.0000,100.0,518.67,642.60,1592.73,1418.58,...,520.45,2388.21,8119.30,8.4546,0.03,392,2388,100.00,38.74,23.2000
113,1,114,35,35.0026,0.8400,100.0,449.44,556.07,1364.28,1136.49,...,182.57,2387.83,8057.58,9.3308,0.02,335,2223,100.00,14.78,8.7806
114,1,115,34,20.0045,0.7013,100.0,491.19,608.28,1481.57,1267.61,...,314.63,2388.13,8047.51,9.3039,0.02,368,2324,100.00,24.20,14.5302
115,1,116,33,24.9980,0.6200,60.0,462.54,536.47,1267.58,1058.31,...,164.87,2027.97,7864.76,10.9242,0.02,309,1915,84.93,14.06,8.7042
116,1,117,32,25.0000,0.6219,60.0,462.54,536.52,1263.31,1048.66,...,164.11,2028.00,7866.28,10.9520,0.02,309,1915,84.93,14.22,8.5179
117,1,118,31,35.0030,0.8400,100.0,449.44,555.76,1373.37,1140.43,...,182.88,2387.77,8050.26,9.3875,0.02,335,2223,100.00,14.83,8.9242
118,1,119,30,25.0056,0.6200,60.0,462.54,537.29,1266.53,1061.97,...,164.87,2027.95,7861.75,10.9068,0.02,307,1915,84.93,14.31,8.5953
119,1,120,29,34.9991,0.8409,100.0,449.44,555.99,1369.65,1144.41,...,182.38,2387.85,8058.79,9.3749,0.02,335,2223,100.00,14.79,8.8366